services:
  - type: web
    name: royalpalms-kjopergruppe
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python seed.py && gunicorn app:app"
    region: frankfurt
    disk:
      name: royal-palms-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: PERSISTENT_DIR
        value: /var/data
